### ISSUE TITLE
Portrait images not displaying in Wiki

### ISSUE THREAD

**Issue by POpus** [splitbrain/slika#10]
Originally reported as a bug here => https://github.com/dokuwiki/dokuwiki/issues/4250

The **'ignore_transparent'** parameter in the php function **imagerotate** has been depreciated in PHP 8.3.0.  As a result, the images in my wiki which are in portrait mode are not displaying because the function is crashing.

2024-03-28 20:47:54	/var/www/cabwiki/vendor/splitbrain/slika/src/GdAdapter.php(96)	ArgumentCountError: imagerotate() expects exactly 3 arguments, 4 given
  #0 /var/www/cabwiki/vendor/splitbrain/slika/src/GdAdapter.php(96): imagerotate()
  #1 /var/www/cabwiki/vendor/splitbrain/slika/src/GdAdapter.php(69): splitbrain\slika\GdAdapter->rotate()
  #2 /var/www/cabwiki/inc/media.php(1799): splitbrain\slika\GdAdapter->autorotate()
  #3 /var/www/cabwiki/inc/media.php(1841): media_mod_image()
  #4 /var/www/cabwiki/lib/exe/fetch.php(102): media_crop_image()
  #5 {main}

I modified GdAdapter.php just now by deleting the $transparency parameter and it is working fine.  Don't know if there are any consequences in doing this.

 Attached are Portrait and Landscape images from my phone whereas the Portrait image was not displaying.

![Portrait](https://github.com/splitbrain/slika/assets/16612652/d0c47986-ee76-45ef-a368-0bfbb525d533)
![Landscape](https://github.com/splitbrain/slika/assets/16612652/d2a1aa6c-6380-49ca-b74e-2ab6db59fdf4)

**Comment by splitbrain** [comment]
This has already been fixed in #9 9
