### ISSUE TITLE
Have a way to inject the rotation from the outside

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/slika#3]
Currently the gdAdapter relies on having exif available in PHP. For the use in DokuWiki we need a way to make it aware of our JPEGMeta class. Maybe by passing a callback? Or by being able to override the adapters returned by the factory?

**Comment by splitbrain** [comment]
The lib now has a PHP only way to determine the rotation, so we don't really need this anymore.

**Comment by EionRobb** [comment]
Thanks for the ping about the gist 👍
