### ISSUE TITLE
ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range

### ISSUE THREAD

**Issue by mprins** [splitbrain/slika#5]
Seeing the below message in my error logs. I suspect invalid input from somewhere, any hints how to find out what image/url is causing this?
 
```
ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range
/data/www/wild-water.nl/www/dokuwiki/vendor/splitbrain/slika/src/GdAdapter.php(238)
#0 /data/www/wild-water.nl/www/dokuwiki/vendor/splitbrain/slika/src/GdAdapter.php(238): imagecolorsforindex()
#1 /data/www/wild-water.nl/www/dokuwiki/vendor/splitbrain/slika/src/GdAdapter.php(382): splitbrain\slika\GdAdapter->createImage()
#2 /data/www/wild-water.nl/www/dokuwiki/vendor/splitbrain/slika/src/GdAdapter.php(128): splitbrain\slika\GdAdapter->resizeOperation()
#3 /data/www/wild-water.nl/www/dokuwiki/inc/media.php(1723): splitbrain\slika\GdAdapter->resize()
#4 /data/www/wild-water.nl/www/dokuwiki/inc/media.php(1748): media_mod_image()
#5 /data/www/wild-water.nl/www/dokuwiki/lib/exe/fetch.php(102): media_resize_image()
#6 {main}
```

https://github.com/splitbrain/slika/blob/be0785cb6b7def847df5d92e0e5fde57def7220f/src/GdAdapter.php#L236-L239

Throwing the `ValueError` is new behaviour since php 8 (before it would return `false`), not sure that is relevant though... looking at DW it seems to be an SVG: https://github.com/splitbrain/dokuwiki/blob/93295a9238ece3133ab213d4edf18b5c29da5025/lib/exe/fetch.php#L92-L105

**Comment by splitbrain** [comment]
Hmm, an SVG shouldn't be passed to Slika at all. Can you confirm, that `$data['file']` is indeed pointing to an SVG? If so this should should probably be reported in DokuWiki.

Also can you check what the value of  `$transcolorindex` is?

**Comment by splitbrain** [comment]
Looking more at the code, this part should only be executed for GIF files. But yeah, the value of `$transcolorindex` would be interesting. Also if you could provide the image file causing the error it would be helpful.

**Comment by sromeroi** [comment]
I have my error log files also plenty of similar errors.

```
2023-10-21 11:11:37     /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(238)       
   ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range
  #0 /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(238): imagecolorsforindex()
  #1 /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(382): splitbrain\slika\GdAdapter->createImage()
  #2 /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(139): splitbrain\slika\GdAdapter->resizeOperation()
  #3 /var/www/wiki/public_html/inc/media.php(1723): splitbrain\slika\GdAdapter->crop()
  #4 /var/www/wiki/public_html/inc/media.php(1764): media_mod_image()
  #5 /var/www/wiki/public_html/lib/exe/fetch.php(100): media_crop_image()
  #6 {main}
```

I don't know which values are causing it or how to reproduce it so I left today a fopen+fwrite there to log the different `$transcolorindex` values. After a few visits I found all the values to be "-1". I'll come back if I some visitor hits the image that is causing the message...

I also temporarily added a `protected $imagepath` property to the class and I'm storing there the image path (as received in `__construct()`) to be able to identify also the problematic file and attach it here for testing.
 
Thanks.

**Comment by sromeroi** [comment]
Dear @splitbrain,

 I found the image causing the error message:

<img width="622" alt="image" src="https://github.com/splitbrain/slika/assets/4025149/e0478194-d613-4531-b107-2f9870519255">


In case you want to reproduce it locally, you can download the image from:

[GIF Image hardware_1.7.gif](https://wiki.speccy.org//_media/hardware/hardware1_7.gif)

NGINX Log line with the URI that triggers the issue (according to the User-Agent, the request came from a bot named `AhrefsBot/7.0`):

`"GET /_media/hardware/hardware1_7.gif?cache=&w=160&h=120&tok=8fba31 HTTP/1.1" 200 371 "-" "`

Visiting that URL produces the error that you can see in the screenshot above and this log line in DokuWiki's error log:

```
# cat wiki/public_html/data/log/error/2023-10-26.log
2023-10-26 06:53:49     /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(249)       
   ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range
  #0 /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(249): imagecolorsforindex()
  #1 /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(393): splitbrain\slika\GdAdapter->createImage()
  #2 /var/www/wiki/public_html/vendor/splitbrain/slika/src/GdAdapter.php(142): splitbrain\slika\GdAdapter->resizeOperation()
  #3 /var/www/wiki/public_html/inc/media.php(1723): splitbrain\slika\GdAdapter->crop()
  #4 /var/www/wiki/public_html/inc/media.php(1764): media_mod_image()
  #5 /var/www/wiki/public_html/lib/exe/fetch.php(100): media_crop_image()
  #6 {main}
```

This is the output produced by my `fwrite()` (filename, `gettype($transcolorindex)` and its value):

`FILE: '/var/www/wiki/public_html/data/media/hardware/hardware1_7.gif' TYPE: 'integer' VALUE: '255'`

Please let me know if you need any additional information or tests.

Best regards
