### ISSUE TITLE
ImageMagickAdapter.php

### ISSUE THREAD

**Issue by sinkva** [splitbrain/slika#8]
I'm trying to use ImageMagick (and apparently ImageMagickAdapter) to speed up the display of thumbnails in my dokuwiki image gallery, but the error log reports:
2023-09-09 02:05:46 .../vendor/splitbrain/slika/src/ImageMagickAdapter.php(119) TypeError: array_map(): Argument #1 ($callback) must be a valid callback or null, function "escapeshellarg" not found or invalid function name

and dokuwiki displays an empty box instead of a thumbnail.

I'm not sure if this is a problem with ImageMagickAdapter.php, or the way ImageMagick is configured, or the way dokuwiki is set up...
I'm not even sure how ImageMagickAdapter.php got installed in the 'vendor' subdirectory.

TIA!

**Comment by splitbrain** [comment]
Your PHP is missing a crucial function. escapeshellargs should be available. ask your provider about it.

**Comment by sinkva** [comment]
Our web hosting is from Midphase, and sadly, their response was: "Unfortunately escapeshellarg php function can not be enabled on our shared hosting". Changing hosting providers is not an option, but I'd  love to get Imagemagick working. Is there any way to modify slika to accommodate lack of the escapeshellarg function?

**Comment by splitbrain** [comment]
no. they probably block additional functions needed anyway
